### ISSUE TITLE
cpals_core() c++ file missing?

### ISSUE THREAD

**Issue by liujiang96** [andrewssobral/mtt#1]
`if (isa(X,'sptensor') || isa(X,'tensor')) && (exist('cpals_core','file') == 3)

```
%fprintf('Using C++ code\n');
[lambda,U] = cpals_core(X, Uinit, fitchangetol, maxiters, dimorder);
P = ktensor(lambda,U);
```

else
...
end`
It seems that cpals_core(...) is a c++ implementation of cp als , but I cannot find the cpp file anywhere.
Is it missing or it does not exist at all?

**Comment by andrewssobral** [comment]
Hi @liujiang96 thank you for your opened issue and sorry for my delayed response. I will check this bug and I will let you updated. Best regards.

**Comment by andrewssobral** [comment]
Hi @liujiang96 it seems that **cpals_core** function is not provided in the Tensor Toolbox:
http://www.sandia.gov/~tgkolda/TensorToolbox/
You can contact Tamara Kolda (tgkolda@sandia.gov) about this.
Best regards,
Andrews

**Comment by andrewssobral** [comment]
There is a Python implementation of CP ALS here:
https://github.com/mnick/scikit-tensor/blob/master/sktensor/cp.py
